### ISSUE TITLE
Cursor position in the editor is jumping around after installation

### ISSUE THREAD

**Issue by twu027** [HugoOM/sfdx_autoheader#46] opened 2021-07-20 22:38 UTC
Uninstall this extension will solve the issue. 
It happens to my old and new computers. 
While I am typing, the cursor moves itself to a random position. So mess up all my typing. 
I don't know how to show you this in action, maybe recording a video for you?

**Comment by HugoOM** [comment] 2021-07-20 22:44
Hi @twu027, 

Thanks for taking the time to fill this issue. A video could certainly work :) 

Would you please be able to also provide a list of your installed extensions?

SFDoc "triggers" are only tied to saving a file or explicitly calling one of its commands, hence it shouldn't have any effect on simply typing in code. I'm wondering if there isn't a conflict with another extension that you have installed - having a list of those could certainly help me look at potential sources for this issue.

Thanks again for your time!

**Comment by twu027** [comment] 2021-07-20 23:00
I figured that out. @HugoOM, if you turn on the autosave, you will have the same issue. I turned on the AutoSave setting in VS code. If I turn that off, it worked correctly, Is there something we can do to make it still work with autosave on?

**Comment by HugoOM** [comment] 2021-07-20 23:14
@twu027 There seems to be a mistake in the file header's "length in rows" that'll push the cursor a few lines too low instead of resetting it to its orignal position. I'll take care of that. 

Once the file header is correctly inserter though, unfortunaltely I am unable to reproduce on my end. Further saving (either imperatively or through VSCode's autosate "afterDelay" setting do not cause my cursor to move around.

Seeing it my help, as well as any other details about your context and installed extensions.

**Comment by HugoOM** [comment] 2021-07-31 00:15
Hi @twu027, 

Are you still able to reproduce the behavior? 

Would you be able to provide further details if that is the case? 

Thanks again,
Hugo

**Comment by HugoOM** [comment] 2021-08-04 16:41
Hi @twu027, 

I will be closing this issue for now as the current information is unfortunately insufficient for me to be able to track down & debug the issue. 

Hopefully it has resolved itself by now, but if that's not the case you're more than welcome to open up a new issue in the future. 

Thanks,
Hugo

**Closed by HugoOM** 2021-08-04 16:41 UTC
